package com.iot.motion.domain.model;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

@Entity
@Table(name = "conf_room")
public class ConfRoom {
		
	// An autogenerated id (unique for each row in the db)
	  @Id
	  @GeneratedValue(strategy = GenerationType.AUTO)
	  private long id;
	  
	  @NotNull
	  private String name;
	  @NotNull
	  private boolean status;
	  
	  //public methods
	  
	  public ConfRoom() { }
	  
	  
	  
	  public long getId() {
		return this.id;
	  }

	  public void setId(long id) {
		this.id = id;
	  }



	public ConfRoom(long id) {
		  this.id = id; 
	  }
	  public ConfRoom(String name){
		  this.name = name;
	  }
	  
	  public void setName(String name){
		  this.name = name;
	  }
	  
	  public String getName(){
		  return this.name;
	  }

	  public boolean isStatus() {
		return status;
	  }

	  public void setStatus(boolean status) {
		this.status = status;
	  }
	  
	  

}
