package com.iot.motion.domain.model;

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Null;

@Entity
@Table(name = "conf_room_event")
public class ConfRoomEvent {
		// An autogenerated id (unique for each row in the db)
		  @Id
		  @GeneratedValue(strategy = GenerationType.AUTO)
		  private long id;
		  
		  @NotNull
		  private long confRoomId;
		  @NotNull
		  private Date inTime;
		  @Null
		  private Date outTime;
		  
		
		//public methods
		  
		public ConfRoomEvent() { }
		
		public ConfRoomEvent(long confRoomId,Date inTime,Date outTime) {
			this.confRoomId = confRoomId;
			this.inTime = inTime;
			this.outTime = outTime;
		}
		  
		public long getConfRoomId() {
			return confRoomId;
		}
		public void setConfRoomId(long confRoomsId) {
			this.confRoomId = confRoomsId;
		}
		public Date getInTime() {
			return inTime;
		}
		public void setInTime(Date inTime) {
			this.inTime = inTime;
		}
		public Date getOutTime() {
			return outTime;
		}
		public void setOutTime(Date outTime) {
			this.outTime = outTime;
		}
}
