package com.iot.motion.domain.model;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

@Entity
@Table(name = "user")
public class User {

  // An autogenerated id (unique for each user in the db)
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private long id;
  
  @NotNull
  private String email;
  
  @NotNull
  private String name;

  // Public methods
  
  public User() { }

  public User(long id) { 
    this.id = id;
  }
  
  public User(String email, String name) {
    this.email = email;
    this.name = name;
  }

  public void setId(long id){
	  this.id = id;
  }
  public long getId(){
	  return this.id;
  }
  public void setEmail(String email){
	  this.email = email;
  }
  public String getEmail(){
	  return this.email;
  }
  public void setName(String name){
	  this.name = name;
  }
  public String getName(){
	  return this.name;
  }

}
